name: Keep Streamlit App Awake

on:
  schedule:
    # This runs the script automatically every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows you to run it manually if you ever want to

jobs:
  ping-repo:
    runs-down: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Make a dummy change to trigger Streamlit
      run: |
        echo "$(date)" > keep_alive.txt

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add keep_alive.txt
        git commit -m "Automated keep-alive ping"
        git push
